Models/Sensor/CreateSensorDto.cs
namespace GateEntryExit_MVC.Models.Sensor
{
    public class CreateSensorDto
    {
        public Guid GateId { get; set; }

        public string Name { get; set; }
    }
}

Models/Sensor/GetAllSensorWithDetailsInputDto.cs
using GateEntryExit_MVC.Models.Shared;

namespace GateEntryExit_MVC.Models.Sensor
{
    public class GetAllSensorWithDetailsInputDto : GetAllDto
    {
        public Guid[] GateIds { get; set; }

        public string GateIdsString { get; set; }

        public DateTime? FromDate { get; set; } 

        public DateTime? ToDate { get; set; }
    }
}

Models/Sensor/GetAllSensorWithDetailsOutputDto.cs
namespace GateEntryExit_MVC.Models.Sensor
{
    public class GetAllSensorWithDetailsOutputDto
    {
        public int TotalCount { get; set; }

        public List<SensorDetailsDto> Items { get; set; }
    }
}

Models/Sensor/GetAllSensorWithDetailsReportInputDto.cs
namespace GateEntryExit.Dtos.Sensor
{
    public class GetAllSensorWithDetailsReportInputDto
    {
        public Guid[] GateIds { get; set; }

        public DateTime? FromDate { get; set; }

        public DateTime? ToDate { get; set; }
    }
}

Models/Sensor/GetAllSensorsDto.cs
namespace GateEntryExit_MVC.Models.Sensor
{
    public class GetAllSensorsDto
    {
        public int TotalCount { get; set; }

        public List<SensorDetailsDto> Items { get; set; }
    }
}

Models/Sensor/SensorCrudWithList.cs
namespace GateEntryExit_MVC.Models.Sensor
{
    public class SensorCrudWithList
    {
        public GetAllSensorsDto Sensors { get; set; }

        public SensorDetailsDto SensorDetails { get; set; }

        public int PageNumber { get; set; }
    }
}

Models/Sensor/SensorDetailsDto.cs
using GateEntryExit_MVC.Models.Gate;

namespace GateEntryExit_MVC.Models.Sensor
{
    public class SensorDetailsDto
    {
        public Guid? Id { get; set; }

        public string Name { get; set; }

        public GateDetailsDto GateDetails { get; set; }
    }
}

Models/Sensor/SensorWithDetailsCrudWithList.cs
namespace GateEntryExit_MVC.Models.Sensor
{
    public class SensorWithDetailsCrudWithList
    {
        public GetAllSensorWithDetailsOutputDto SensorWithDetailsOutput { get; set; }

        public GetAllSensorWithDetailsInputDto SensorWithDetailsInput { get; set; }
    }
}

Models/Sensor/UpdateSensorDto.cs
namespace GateEntryExit_MVC.Models.Sensor
{
    public class UpdateSensorDto
    {
        public Guid Id { get; set; }

        public string Name { get; set; }
    }
}

Controllers/GateModalController.cs
using GateEntryExit_MVC.Services.Gate;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace GateEntryExit_MVC.Controllers
{
    public class GateModalController : Controller
    { 
        private readonly IGateService _gateService;

        public GateModalController(IGateService gateService)
        {
            _gateService = gateService;
        }

        [HttpPost]
        public async Task<IActionResult> FetchGates(int pageNumber = 1,
            bool isSingleSelection = true,  
            Guid? selectedGateValue = null,
            [FromBody] Guid[] selectedGateValues = null)
        {
            var allGates = await _gateService.GetAllAsync(pageNumber);
            Guid[] gateIds = new Guid[0];

            if (selectedGateValues != null)
            {
                gateIds = selectedGateValues;
            }

            return View(new { 
                gates = allGates, 
                selectedGate = selectedGateValue,
                selectedGates = gateIds,
                isSingleSelect = isSingleSelection 
            });
        }
    }
}

Controllers/SensorController.cs
using GateEntryExit.Dtos.Sensor;
using GateEntryExit_MVC.Helpers;
using GateEntryExit_MVC.Models.Gate;
using GateEntryExit_MVC.Models.GateExit;
using GateEntryExit_MVC.Models.Sensor;
using GateEntryExit_MVC.Models.Shared;
using GateEntryExit_MVC.Services;
using Microsoft.AspNetCore.Mvc;
using System.Reflection;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace GateEntryExit_MVC.Controllers
{
    public class SensorController : Controller
    {
        private readonly IHttpClientService _httpClientService;

        public SensorController(IHttpClientService httpClientService)
        {
            _httpClientService = httpClientService;
        }

        public async Task<IActionResult> GetAll(int pageNumber = 1)
        {
            var allSensors = await GetAllAsync(pageNumber);
            return View("~/Views/Sensor/GetAll.cshtml", new SensorCrudWithList()
            {
                SensorDetails = new SensorDetailsDto() { 
                    Id = null , 
                    GateDetails = new GateDetailsDto()
                    {
                        Id = null,
                        Name = ""
                    },
                    Name = ""
                },
                Sensors = allSensors,
                PageNumber = Request.Query["pageNumber"].FirstOrDefault() != null ? Convert.ToInt32(Request.Query["pageNumber"]) : 1
            });
        }

        private async Task<GetAllSensorsDto> GetAllAsync(int pageNumber = 1)
        {
            var maxResultCount = 5;
            var skipCount = (pageNumber - 1) * maxResultCount;
            var allSensors = new GetAllSensorsDto();
            var endpoint = ApiEndpoints.baseUrl + ApiEndpoints.sensorGetAll;
            var postData = new GetAllDto { MaxResultCount = maxResultCount, SkipCount = skipCount, Sorting = "" };
            return await _httpClientService.GetAllAsync(allSensors, postData, endpoint);
        }

        public async Task<IActionResult> GetAllWithDetails(SensorWithDetailsCrudWithList sensorWithDetailsCrudWithListModel,
            int pageNumber = 1,
            string gateIds = "")
        {
            // gateIds empty on pageload getAll
            // gateIds empty on filter button form submit
            // gateIds has value after filtering, value comes from pagination

            var maxResultCount = 5;
            var skipCount = (pageNumber - 1) * maxResultCount;
            var sensorWithDetailsInput = new GetAllSensorWithDetailsInputDto()
                                        {
                                            FromDate = null,
                                            ToDate = null,
                                            GateIds = new Guid[0],
                                            GateIdsString = "",
                                            MaxResultCount = maxResultCount,
                                            SkipCount = skipCount,
                                            Sorting = ""
                                        };

            // this part to handle pagination on filtered results
            if (!string.IsNullOrEmpty(gateIds))
            {
                sensorWithDetailsInput.GateIds = ConvertToGuidArray(gateIds);
                sensorWithDetailsInput.GateIdsString = gateIds;
            }

            // below code executed when filter button clicked calling form action
            if (sensorWithDetailsCrudWithListModel.SensorWithDetailsInput != null)
            {
                sensorWithDetailsInput = new GetAllSensorWithDetailsInputDto()
                {
                    FromDate = sensorWithDetailsCrudWithListModel.SensorWithDetailsInput.FromDate,
                    ToDate = sensorWithDetailsCrudWithListModel.SensorWithDetailsInput.ToDate,
                    GateIdsString = sensorWithDetailsCrudWithListModel.SensorWithDetailsInput.GateIdsString,
                    MaxResultCount = maxResultCount,
                    SkipCount = skipCount,
                    Sorting = ""
                };
                sensorWithDetailsInput.GateIds = ConvertToGuidArray(sensorWithDetailsCrudWithListModel.SensorWithDetailsInput.GateIdsString);
            }

            var allSensors = await GetAllWithDetailsAsync(sensorWithDetailsInput, pageNumber);
            return View("~/Views/Sensor/GetAllWithDetails.cshtml", new SensorWithDetailsCrudWithList()
            {
                SensorWithDetailsInput = sensorWithDetailsInput,
                SensorWithDetailsOutput = allSensors,                 
            });
        }

        private static Guid[] ConvertToGuidArray(string guidString)
        {
            if (string.IsNullOrEmpty(guidString))
            {
                return new Guid[0];
            }
            else
            {
                string[] guidStrings = guidString.Split(',');
                Guid[] guids = new Guid[guidStrings.Length];

                for (int i = 0; i < guidStrings.Length; i++)
                {
                    guids[i] = Guid.Parse(guidStrings[i]);
                }

                return guids;
            }
        }

        private async Task<GetAllSensorWithDetailsOutputDto> GetAllWithDetailsAsync(GetAllSensorWithDetailsInputDto sensorWithDetailsInput,
            int pageNumber = 1)
        {           
            var model = new GetAllSensorWithDetailsOutputDto();
            var endpoint = ApiEndpoints.baseUrl + ApiEndpoints.sensorGetAllWithDetails;
            var postData = sensorWithDetailsInput;
            return await _httpClientService.GetAllAsync(model, postData, endpoint);            
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid id, int pageNumber)
        {
            var sensorDetail = new SensorDetailsDto();
            var endpoint = ApiEndpoints.baseUrl + ApiEndpoints.sensorGetById.Replace("{id}", "") + id;
            sensorDetail = await _httpClientService.GetAsync(sensorDetail, endpoint);

            var allSensors = await GetAllAsync(pageNumber);
            return View("~/Views/Sensor/GetAll.cshtml", new SensorCrudWithList()
            {
                SensorDetails = sensorDetail,
                Sensors = allSensors,
                PageNumber = Request.Query["pageNumber"].FirstOrDefault() != null ? Convert.ToInt32(Request.Query["pageNumber"]) : 1
            });
        }

        [HttpPost]
        public async Task<IActionResult> AddOrEdit(Guid? id, SensorCrudWithList sensorCrudWithListModel)
        {
            var model = sensorCrudWithListModel.SensorDetails;
            if (id == null)
            {
                var postData = new CreateSensorDto() { Name = model.Name, GateId = model.GateDetails.Id.Value };
                var endpoint = ApiEndpoints.baseUrl + ApiEndpoints.sensorCreate;
                await _httpClientService.CreateAsync(model, postData, endpoint);
            }
            else
            {
                var postData = new UpdateSensorDto() { Name = model.Name, Id = model.Id.Value };
                var endpoint = ApiEndpoints.baseUrl + ApiEndpoints.sensorEdit;
                await _httpClientService.EditAsync(model, postData, endpoint);
            }
            return RedirectToAction("GetAll");
        }

        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id != null)
            {
                var endpoint = ApiEndpoints.baseUrl + ApiEndpoints.sensorDelete.Replace("{id}", "") + id;
                await _httpClientService.DeleteAsync(endpoint);
            }
            return RedirectToAction("GetAll");
        }

        public async Task<IActionResult> EmailReport()
        {
            var endpoint = ApiEndpoints.baseUrl + ApiEndpoints.sensorExcelReport;
            var postData = new GetAllSensorWithDetailsReportInputDto()
            {
                FromDate = null,
                ToDate = null,
                GateIds = new Guid[0]
            };
            await _httpClientService.PostAsync(postData, endpoint);
            return RedirectToAction("GetAll");
        }

        public async Task<IActionResult> PdfReport()
        {
            var endpoint = ApiEndpoints.baseUrl + ApiEndpoints.sensorPdfReport;
            var postData = new GetAllSensorWithDetailsReportInputDto()
            {
                FromDate = null,
                ToDate = null,
                GateIds = new Guid[0]
            };
            await _httpClientService.PostAsync(postData, endpoint);
            return RedirectToAction("GetAllWithDetails");
        }
    }
}

ViewComponents/PaginationViewComponent.cs
using GateEntryExit_MVC.Models.Shared;
using Microsoft.AspNetCore.Mvc;

namespace GateEntryExit_MVC.ViewComponents
{
    public class PaginationViewComponent : ViewComponent
    {
        public PaginationViewComponent()
        {
            
        }

        public async Task<IViewComponentResult> InvokeAsync(PaginationModel model)
        {
            return View("~/ViewComponents/PaginationView.cshtml", model);
        }
    }
}

Views/Sensor/GetAll.cshtml
@using GateEntryExit_MVC.Models.Sensor
@using GateEntryExit_MVC.Models.Shared

@model SensorCrudWithList

@{
    var totalItems = Model.Sensors.TotalCount;
    var items = Model.Sensors.Items;
}

<div class="container">
    <div class="row">
        <div class="col-6">

            <h3>Sensor</h3>

            <form id="sensorAddOrEdit" asp-controller="Sensor" asp-action="AddOrEdit" method="post" asp-route-id="@Model.SensorDetails.Id">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="SensorDetails.Id" />

                <div class="form-group">
                    <input asp-for="SensorDetails.Name" class="form-control" placeholder="Enter sensor name"/>
                    <span asp-validation-for="SensorDetails.Name" class="text-danger"></span>
                </div>

                <input type="hidden" asp-for="SensorDetails.GateDetails.Id" id="selectedGateValue" />
                <div class="form-group">
                    <div class="input-group mb-3">
                        <input disabled asp-for="SensorDetails.GateDetails.Name" class="form-control" id="selectedGateName" placeholder="Select a gate" />
                        <div class="input-group-append">
                            <button class="btn btn-primary" onclick="showGateModal(event, '@Url.Action("FetchGates", "GateModal", new { pageNumber = 1 }, Context.Request.Scheme)','All gates', true, false)">Gates</button>
                        </div>
                    </div>                    
                    <span asp-validation-for="SensorDetails.GateDetails.Name" class="text-danger"></span>
                </div>

                @await Html.PartialAsync("~/Views/Shared/PartialViews/GateModalPartialView.cshtml")

                <div class="form-group mt-3">
                    <input type="submit" value="Save" class="btn btn-primary" />
                </div>
            </form>
            
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Actions</th>
                        <th>
                            Sensor name
                        </th>
                        <th>
                            Gate name
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var sensor in items)
                    {
                        <tr>
                            <td>
                                <button class="btn btn-primary" onclick="location.href='@Url.Action("Edit", "Sensor", new { id = sensor.Id, pageNumber = Model.PageNumber }, Context.Request.Scheme)'">Edit</button>
                                <button class="btn btn-danger" onclick="location.href='@Url.Action("Delete", "Sensor", new { id = sensor.Id }, Context.Request.Scheme)'">Delete</button>
                            </td>
                            <td>@sensor.Name</td>
                            <td>@sensor.GateDetails.Name</td>
                        </tr>
                    }
                </tbody>
            </table>
            @await Component.InvokeAsync("Pagination", new PaginationModel(){
               Controller = "Sensor",
               Action = "GetAll",
               TotalItems = totalItems
            })
        </div>
    </div>
</div>
   

Views/Sensor/GetAllWithDetails.cshtml
@using GateEntryExit_MVC.Models.Sensor
@using GateEntryExit_MVC.Models.Shared

@model SensorWithDetailsCrudWithList

@{
    var pageSize = 5;
    var totalItems = Model.SensorWithDetailsOutput.TotalCount;
    var items = Model.SensorWithDetailsOutput.Items;
    var totalPages = (int)Math.Ceiling(totalItems / (double)pageSize);
}

<div class="container">
    <div class="row">
        <div class="col-6">
            <div>
                <h3 class="d-inline-block">Sensor with Details</h3>
                <div class="float-end">
                    <button class="btn btn-primary" onclick="location.href='@Url.Action("EmailReport", "Sensor", null, Context.Request.Scheme)'">Email</button>
                    <button class="btn btn-danger" onclick="location.href='@Url.Action("PdfReport", "Sensor", null, Context.Request.Scheme)'">Pdf</button>
                </div>               
            </div>
            
            <form asp-controller="Sensor" asp-action="GetAllWithDetails">
                <input type="hidden" asp-for="SensorWithDetailsInput.GateIdsString" id="selectedGateValues" />
                 
                <button class="btn btn-primary"
                        onclick="showGateModal(event, '@Url.Action("FetchGates", "GateModal", new { pageNumber = 1 , isSingleSelection = false }, Context.Request.Scheme)','All gates', false, false)">
                    Gates
                </button>

                <input type="submit" value="Filter" class="btn btn-primary" />

                @await Html.PartialAsync("~/Views/Shared/PartialViews/GateModalPartialView.cshtml")
            </form>

            <div id="selectedGateNames" class="mt-3 mb-3">Selected gates - </div>

            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>
                            Sensor name
                        </th>
                        <th>
                            Gate name
                        </th>
                        <th>
                            Entry count
                        </th>
                        <th>
                            Exit count
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var sensor in items)
                    {
                        <tr>
                            <td>@sensor.Name</td>
                            <td>@sensor.GateDetails.Name</td>
                            <td>@sensor.GateDetails.EntryCount</td>
                            <td>@sensor.GateDetails.ExitCount</td>
                        </tr>
                    }
                </tbody>
            </table>
            <nav>
                <ul class="pagination justify-content-end">
                    @for (int i = 1; i <= totalPages; i++)
                    {
                        <li class="page-item">
                            <a class="page-link" asp-area="" asp-controller="Sensor" asp-action="GetAllWithDetails" asp-route-pageNumber="@i" asp-route-gateIds="@Model.SensorWithDetailsInput.GateIdsString">@i</a>
                        </li>
                    }
                </ul>
            </nav>
        </div>
    </div>
</div>
   