Models/GateEntry/CreateGateEntryDto.cs
namespace GateEntryExit_MVC.Models.GateEntry
{
    public class CreateGateEntryDto
    {
        public Guid GateId { get; set; }

        public DateTime TimeStamp { get; set; }

        public int NumberOfPeople { get; set; }
    }
}

Models/GateEntry/GateEntryCrudWithList.cs
namespace GateEntryExit_MVC.Models.GateEntry
{
    public class GateEntryCrudWithList
    {
        public GetAllGateEntriesDto GateEntries { get; set; }

        public GateEntryDto GateEntry { get; set; }

        public int PageNumber { get; set; }
    }
}

Models/GateEntry/GateEntryDto.cs
using System.ComponentModel.DataAnnotations;

namespace GateEntryExit_MVC.Models.GateEntry
{
    public class GateEntryDto
    {
        public Guid? Id { get; set; }

        public Guid? GateId { get; set; }

        [DataType(DataType.Date)]
        public DateTime? Date { get; set; }

        [Range(0, 23)]
        public int? Hour { get; set; }

        [Range(0, 59)]
        public int? Minute { get; set; }

        public DateTime TimeStamp { get; set; }

        public int? NumberOfPeople { get; set; }

        public string GateName { get; set; }
    }
}

Models/GateEntry/GetAllGateEntriesDto.cs
namespace GateEntryExit_MVC.Models.GateEntry
{
    public class GetAllGateEntriesDto
    {
        public int TotalCount { get; set; }

        public List<GateEntryDto> Items { get; set; }
    }
}

Models/GateEntry/UpdateGateEntryDto.cs
namespace GateEntryExit_MVC.Models.GateEntry
{
    public class UpdateGateEntryDto
    {
        public Guid Id { get; set; }

        public DateTime TimeStamp { get; set; }

        public int NumberOfPeople { get; set; }
    }
}

Controllers/GateEntryController.cs
using GateEntryExit_MVC.Helpers;
using GateEntryExit_MVC.Models.Gate;
using GateEntryExit_MVC.Models.GateEntry;
using GateEntryExit_MVC.Models.Sensor;
using GateEntryExit_MVC.Models.Shared;
using GateEntryExit_MVC.Services;
using Microsoft.AspNetCore.Mvc;

namespace GateEntryExit_MVC.Controllers
{
    public class GateEntryController : Controller
    {
        private readonly IHttpClientService _httpClientService;
        public GateEntryController(IHttpClientService httpClientService)
        {
            _httpClientService = httpClientService;
        }

        public async Task<IActionResult> GetAll(int pageNumber = 1)
        {
            var allGateEntry = await GetAllAsync(pageNumber);
            return View("~/Views/GateEntry/GetAll.cshtml", new GateEntryCrudWithList()
            {
                GateEntry = new GateEntryDto()
                {
                    Id = null,
                    GateId = null,
                    GateName = "",
                    NumberOfPeople = null,
                    Date = null,
                    Hour = null,
                    Minute = null,
                },
                GateEntries = allGateEntry,
                PageNumber = Request.Query["pageNumber"].FirstOrDefault() != null ? Convert.ToInt32(Request.Query["pageNumber"]) : 1
            });
        }

        private async Task<GetAllGateEntriesDto> GetAllAsync(int pageNumber = 1)
        {
            var maxResultCount = 5;
            var skipCount = (pageNumber - 1) * maxResultCount;
            var model = new GetAllGateEntriesDto();
            var endpoint = ApiEndpoints.baseUrl + ApiEndpoints.gateEntryGetAll;
            var postData = new GetAllDto { MaxResultCount = maxResultCount, SkipCount = skipCount, Sorting = "" };
            return await _httpClientService.GetAllAsync(model, postData, endpoint);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid id, int pageNumber)
        {
            var gateEntry = new GateEntryDto();
            var endpoint = ApiEndpoints.baseUrl + ApiEndpoints.gateEntryGetById.Replace("{id}", "") + id;
            gateEntry = await _httpClientService.GetAsync(gateEntry, endpoint);

            var allGateEntry = await GetAllAsync(pageNumber);
            return View("~/Views/GateEntry/GetAll.cshtml", new GateEntryCrudWithList()
            {
                GateEntry = new GateEntryDto()
                {
                    Id = gateEntry.Id,
                    GateId = gateEntry.GateId,
                    GateName = gateEntry.GateName,
                    NumberOfPeople = gateEntry.NumberOfPeople,
                    Date = gateEntry.TimeStamp.Date,
                    Hour = gateEntry.TimeStamp.Hour,
                    Minute = gateEntry.TimeStamp.Minute,
                },
                GateEntries = allGateEntry,
                PageNumber = Request.Query["pageNumber"].FirstOrDefault() != null ? Convert.ToInt32(Request.Query["pageNumber"]) : 1
            });
        }

        [HttpPost]
        public async Task<IActionResult> AddOrEdit(Guid? id, GateEntryCrudWithList gateEntryCrudWithListModel)
        {
            var model = gateEntryCrudWithListModel.GateEntry;
            if (id == null)
            {              
                var dateTime = new DateTime(model.Date.Value.Year,
                    model.Date.Value.Month,
                    model.Date.Value.Day,
                    model.Hour.Value,
                    model.Minute.Value,
                    0);
                var postData = new CreateGateEntryDto() { 
                    GateId = model.GateId.Value, 
                    NumberOfPeople = model.NumberOfPeople.Value, 
                    TimeStamp = dateTime
                };
                var endpoint = ApiEndpoints.baseUrl + ApiEndpoints.gateEntryCreate;
                await _httpClientService.CreateAsync(model, postData, endpoint);
            }
            else
            {
                var dateTime = new DateTime(model.Date.Value.Year,
                    model.Date.Value.Month,
                    model.Date.Value.Day,
                    model.Hour.Value,
                    model.Minute.Value,
                    0);
                var postData = new UpdateGateEntryDto() { 
                    Id = model.Id.Value, 
                    NumberOfPeople = model.NumberOfPeople.Value, 
                    TimeStamp = dateTime
                };
                var endpoint = ApiEndpoints.baseUrl + ApiEndpoints.gateEntryEdit;
                await _httpClientService.EditAsync(model, postData, endpoint);
            }
            return RedirectToAction("GetAll");
        }

        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id != null)
            {
                var endpoint = ApiEndpoints.baseUrl + ApiEndpoints.gateEntryDelete.Replace("{id}", "") + id;
                await _httpClientService.DeleteAsync(endpoint);
            }
            return RedirectToAction("GetAll");
        }
    }
}

Controllers/GateModalController.cs
using GateEntryExit_MVC.Services.Gate;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace GateEntryExit_MVC.Controllers
{
    public class GateModalController : Controller
    { 
        private readonly IGateService _gateService;

        public GateModalController(IGateService gateService)
        {
            _gateService = gateService;
        }

        [HttpPost]
        public async Task<IActionResult> FetchGates(int pageNumber = 1,
            bool isSingleSelection = true,  
            Guid? selectedGateValue = null,
            [FromBody] Guid[] selectedGateValues = null)
        {
            var allGates = await _gateService.GetAllAsync(pageNumber);
            Guid[] gateIds = new Guid[0];

            if (selectedGateValues != null)
            {
                gateIds = selectedGateValues;
            }

            return View(new { 
                gates = allGates, 
                selectedGate = selectedGateValue,
                selectedGates = gateIds,
                isSingleSelect = isSingleSelection 
            });
        }
    }
}

ViewComponents/PaginationViewComponent.cs
using GateEntryExit_MVC.Models.Shared;
using Microsoft.AspNetCore.Mvc;

namespace GateEntryExit_MVC.ViewComponents
{
    public class PaginationViewComponent : ViewComponent
    {
        public PaginationViewComponent()
        {
            
        }

        public async Task<IViewComponentResult> InvokeAsync(PaginationModel model)
        {
            return View("~/ViewComponents/PaginationView.cshtml", model);
        }
    }
}

Views/GateEntry/GetAll.cshtml
@using GateEntryExit_MVC.Models.GateEntry
@using GateEntryExit_MVC.Models.Shared

@model GateEntryCrudWithList

@{
    var totalItems = Model.GateEntries.TotalCount;
    var items = Model.GateEntries.Items;
}


<div class="container">
    <div class="row">
        <div class="col-6">
            
            <h3>Gate entry</h3>

            <div class="row">
                <div class="col-md-12">
                    <form asp-controller="GateEntry" asp-action="AddOrEdit" method="post" asp-route-id="@Model.GateEntry.Id">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <input type="hidden" asp-for="GateEntry.Id" />

                        <div class="form-group">
                            <label>Number of people</label>
                            <input type="number" asp-for="GateEntry.NumberOfPeople" placeholder="Number of people" class="form-control" />
                            <span asp-validation-for="GateEntry.NumberOfPeople" class="text-danger"></span>
                        </div>

                        <div class="form-group">
                            <div>
                                <label>Time stamp</label>
                            </div>
                            <div>
                                <input type="date" asp-for="GateEntry.Date" placeholder="Date" />
                                <input type="number" asp-for="GateEntry.Hour" min="00" max="24" placeholder="Hour" />
                                <input type="number" asp-for="GateEntry.Minute" min="00" max="59" placeholder="Minute" />
                            </div>
                        </div>

                        <input type="hidden" asp-for="GateEntry.GateId" id="selectedGateValue" />
                        <div class="form-group">
                            <div class="input-group mb-3">
                                <input disabled asp-for="GateEntry.GateName" class="form-control" id="selectedGateName" placeholder="Select a gate" />
                                <div class="input-group-append">
                                    <button class="btn btn-primary" onclick="showGateModal(event, '@Url.Action("FetchGates", "GateModal", new { pageNumber = 1 }, Context.Request.Scheme)','All gates', true, false)">Gates</button>
                                </div>
                            </div>
                            <span asp-validation-for="GateEntry.GateName" class="text-danger"></span>
                        </div>

                        @await Html.PartialAsync("~/Views/Shared/PartialViews/GateModalPartialView.cshtml")

                        <div class="form-group mt-3">
                            <input type="submit" value="Save" class="btn btn-primary" />
                        </div>
                    </form>
                </div>
            </div>

            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Actions</th>
                        <th>
                            Name
                        </th>
                        <th>
                            NumberOfPeople
                        </th>
                        <th>
                            TimeStamp
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var gateEntry in items)
                    {
                        <tr>
                            <td>
                                <button class="btn btn-primary" onclick="location.href='@Url.Action("Edit", "GateEntry", new { id = gateEntry.Id, pageNumber = Model.PageNumber }, Context.Request.Scheme)'">Edit</button>
                                <button class="btn btn-danger" onclick="location.href='@Url.Action("Delete", "GateEntry", new { id = gateEntry.Id }, Context.Request.Scheme)'">Delete</button>
                            </td>
                            <td>@gateEntry.GateName</td>
                            <td>@gateEntry.NumberOfPeople</td>
                            <td>@gateEntry.TimeStamp</td>
                        </tr>
                    }
                </tbody>
            </table>
            @await Component.InvokeAsync("Pagination", new PaginationModel(){
                Controller = "GateEntry",
                Action = "GetAll",
                TotalItems = totalItems
            })
        </div>
    </div>
</div>
   