Models/Gate/CreateGateDto.cs
namespace GateEntryExit_MVC.Models.Gate
{
    public class CreateGateDto
    {
        public string Name { get; set; }
    }
}

Models/Gate/GateCrudWithList.cs
namespace GateEntryExit_MVC.Models.Gate
{
    public class GateCrudWithList
    {
        public GetAllGatesDto Gates { get; set; }

        public GateDto Gate { get; set; }

        public int PageNumber { get; set; }
    }
}

Models/Gate/GateDetailsDto.cs
namespace GateEntryExit_MVC.Models.Gate
{
    public class GateDetailsDto : GateDto
    {
        public int EntryCount { get; set; }

        public int ExitCount { get; set; }
    }
}

Models/Gate/GateDto.cs
namespace GateEntryExit_MVC.Models.Gate
{
    public class GateDto
    {
        public string Name { get; set; }

        public Guid? Id { get; set; }
    }
}

Models/Gate/GetAllGatesDto.cs
namespace GateEntryExit_MVC.Models.Gate
{
    public class GetAllGatesDto
    {
        public int TotalCount { get; set; }

        public List<GateDetailsDto> Items { get; set; }
    }
}

Models/Gate/UpdateGateDto.cs
namespace GateEntryExit_MVC.Models.Gate
{
    public class UpdateGateDto : GateDto
    {

    }
}

Controllers/GateController.cs
using GateEntryExit_MVC.Models.Gate;
using GateEntryExit_MVC.Helpers;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using GateEntryExit_MVC.Models.Shared;
using System.Text;
using Microsoft.Extensions.Logging;
using System.Reflection;
using GateEntryExit_MVC.Services;
using GateEntryExit_MVC.Services.Gate;

namespace GateEntryExit_MVC.Controllers
{
    public class GateController : Controller
    {      
        private readonly ILogger<GateController> _logger;
        private readonly IHttpClientService _httpClientService;
        private readonly IGateService _gateService;

        public GateController(ILogger<GateController> logger,
            IHttpClientService httpClientService,
            IGateService gateService)
        {           
            _logger = logger;
            _httpClientService = httpClientService;
            _gateService = gateService;
        }

        public async Task<IActionResult> GetAll(int pageNumber = 1)
        {
            var allGates = await _gateService.GetAllAsync(pageNumber);
            return View("~/Views/Gate/GetAll.cshtml", new GateCrudWithList()
            {
                Gate = new GateDto() { Id = null },
                Gates = allGates,
                PageNumber = Request.Query["pageNumber"].FirstOrDefault() != null ? Convert.ToInt32(Request.Query["pageNumber"]) : 1
            });
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid id, int pageNumber)
        {            
            var gate = new GateDto();
            var endpoint = ApiEndpoints.baseUrl + ApiEndpoints.gateGetById.Replace("{id}", "") + id;
            gate = await _httpClientService.GetAsync(gate, endpoint);

            var allGates = await _gateService.GetAllAsync(pageNumber);
            return View("~/Views/Gate/GetAll.cshtml", new GateCrudWithList()
            {
                Gate = gate,
                Gates = allGates,
                PageNumber = Request.Query["pageNumber"].FirstOrDefault() != null ? Convert.ToInt32(Request.Query["pageNumber"]) : 1
            });
        }

        [HttpPost]
        public async Task<IActionResult> AddOrEdit(Guid? id, GateCrudWithList gateCrudWithListModel)
        {
            var model = gateCrudWithListModel.Gate;            
            if (id == null)
            {
                var postData = new CreateGateDto() { Name = model.Name };
                var endpoint = ApiEndpoints.baseUrl + ApiEndpoints.gateCreate;
                await _httpClientService.CreateAsync(model, postData, endpoint);
            }
            else
            {
                var postData = new UpdateGateDto() { Name = model.Name, Id = model.Id };
                var endpoint = ApiEndpoints.baseUrl + ApiEndpoints.gateEdit;
                await _httpClientService.EditAsync(model, postData, endpoint);
            }
            return RedirectToAction("GetAll");
        }

        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id != null)
            {
                var endpoint = ApiEndpoints.baseUrl + ApiEndpoints.gateDelete.Replace("{id}", "") + id;
                await _httpClientService.DeleteAsync(endpoint);
            }
            return RedirectToAction("GetAll");
        }
    }
}

ViewComponents/PaginationViewComponent.cs
using GateEntryExit_MVC.Models.Shared;
using Microsoft.AspNetCore.Mvc;

namespace GateEntryExit_MVC.ViewComponents
{
    public class PaginationViewComponent : ViewComponent
    {
        public PaginationViewComponent()
        {
            
        }

        public async Task<IViewComponentResult> InvokeAsync(PaginationModel model)
        {
            return View("~/ViewComponents/PaginationView.cshtml", model);
        }
    }
}

Views/Gate/GetAll.cshtml
@using GateEntryExit_MVC.Models.Gate
@using GateEntryExit_MVC.Models.Shared
@using Microsoft.AspNetCore.Http

@model GateCrudWithList

@{
    var totalItems = Model.Gates.TotalCount;
    var items = Model.Gates.Items;    
}

<div class="container">
    <div class="row">       
        <div class="col-6">

            <h3>Gate</h3>

            <form asp-controller="Gate" asp-action="AddOrEdit" method="post" asp-route-id="@Model.Gate.Id">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="Gate.Id" />
                <div class="form-group">
                    <div class="input-group mb-3">
                        <input asp-for="Gate.Name" class="form-control" placeholder="Enter gate name" />
                        <div class="input-group-append">
                            <input type="submit" value="Save" class="btn btn-primary" />
                        </div>
                    </div>
                    <span asp-validation-for="Gate.Name" class="text-danger"></span>
                </div>
            </form>

            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Actions</th>
                        <th>
                           Name
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var gate in items)
                    {
                        <tr>
                            <td>
                                <button class="btn btn-primary" onclick="location.href='@Url.Action("Edit", "Gate", new { id = gate.Id, pageNumber = Model.PageNumber }, Context.Request.Scheme)'">Edit</button>
                                <button class="btn btn-danger" onclick="location.href='@Url.Action("Delete", "Gate", new { id = gate.Id }, Context.Request.Scheme)'">Delete</button>
                            </td>
                            <td>@gate.Name</td>
                        </tr>
                    }
                </tbody>
            </table>
            @await Component.InvokeAsync("Pagination", new PaginationModel() { 
                Controller = "Gate",
                Action = "GetAll",
                TotalItems = totalItems
            })
        </div>
    </div>
</div>
   