Models/GateExit/CreateGateExitDto.cs
namespace GateEntryExit_MVC.Models.GateExit
{
    public class CreateGateExitDto
    {

        public Guid GateId { get; set; }

        public DateTime TimeStamp { get; set; }

        public int NumberOfPeople { get; set; }
    }
}

Models/GateExit/GateExitCrudWithList.cs
using GateEntryExit_MVC.Models.GateEntry;

namespace GateEntryExit_MVC.Models.GateExit
{
    public class GateExitCrudWithList
    {
        public GetAllGateExitsDto GateExits { get; set; }

        public GateExitDto GateExit { get; set; }

        public int PageNumber { get; set; }
    }
}

Models/GateExit/GateExitDto.cs
using System.ComponentModel.DataAnnotations;

namespace GateEntryExit_MVC.Models.GateExit
{
    public class GateExitDto
    {
        public Guid? Id { get; set; }

        public Guid? GateId { get; set; }

        public DateTime TimeStamp { get; set; }

        public int? NumberOfPeople { get; set; }

        public string GateName { get; set; }

        [DataType(DataType.Date)]
        public DateTime? Date { get; set; }

        [Range(0, 23)]
        public int? Hour { get; set; }

        [Range(0, 59)]
        public int? Minute { get; set; }
    }
}

Models/GateExit/GetAllGateExitsDto.cs
namespace GateEntryExit_MVC.Models.GateExit
{
    public class GetAllGateExitsDto
    {
        public int TotalCount { get; set; }

        public List<GateExitDto> Items { get; set; }
    }
}

Models/GateExit/UpdateGateExitDto.cs
namespace GateEntryExit_MVC.Models.GateExit
{
    public class UpdateGateExitDto
    {
        public Guid Id { get; set; }

        public DateTime TimeStamp { get; set; }

        public int NumberOfPeople { get; set; }
    }
}

Controllers/GateExitController.cs
using GateEntryExit_MVC.Helpers;
using GateEntryExit_MVC.Models.GateEntry;
using GateEntryExit_MVC.Models.GateExit;
using GateEntryExit_MVC.Models.Shared;
using GateEntryExit_MVC.Services;
using Microsoft.AspNetCore.Mvc;

namespace GateEntryExit_MVC.Controllers
{
    public class GateExitController : Controller
    {
        private readonly IHttpClientService _httpClientService;

        public GateExitController(IHttpClientService httpClientService)
        {
            _httpClientService = httpClientService;
        }

        public async Task<IActionResult> GetAll(int pageNumber = 1)
        {
            var allGateExit = await GetAllAsync(pageNumber);
            return View("~/Views/GateExit/GetAll.cshtml", new GateExitCrudWithList()
            {
                GateExit = new GateExitDto()
                {
                    Id = null,
                    GateId = null,
                    GateName = "",
                    NumberOfPeople = null,
                    Date = null,
                    Hour = null,
                    Minute = null,
                },
                GateExits = allGateExit,
                PageNumber = Request.Query["pageNumber"].FirstOrDefault() != null ? Convert.ToInt32(Request.Query["pageNumber"]) : 1
            });
        }

        private async Task<GetAllGateExitsDto> GetAllAsync(int pageNumber = 1)
        {
            var maxResultCount = 5;
            var skipCount = (pageNumber - 1) * maxResultCount;
            var model = new GetAllGateExitsDto();
            var endpoint = ApiEndpoints.baseUrl + ApiEndpoints.gateExitGetAll;
            var postData = new GetAllDto { MaxResultCount = maxResultCount, SkipCount = skipCount, Sorting = "" };
            return await _httpClientService.GetAllAsync(model, postData, endpoint);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid id, int pageNumber)
        {
            var gateExit = new GateExitDto();
            var endpoint = ApiEndpoints.baseUrl + ApiEndpoints.gateExitGetById.Replace("{id}", "") + id;
            gateExit = await _httpClientService.GetAsync(gateExit, endpoint);

            var allGateExit = await GetAllAsync(pageNumber);
            return View("~/Views/GateExit/GetAll.cshtml", new GateExitCrudWithList()
            {
                GateExit = new GateExitDto()
                {
                    Id = gateExit.Id,
                    GateId = gateExit.GateId,
                    GateName = gateExit.GateName,
                    NumberOfPeople = gateExit.NumberOfPeople,
                    Date = gateExit.TimeStamp.Date,
                    Hour = gateExit.TimeStamp.Hour,
                    Minute = gateExit.TimeStamp.Minute,
                },
                GateExits = allGateExit,
                PageNumber = Request.Query["pageNumber"].FirstOrDefault() != null ? Convert.ToInt32(Request.Query["pageNumber"]) : 1
            });
        }

        [HttpPost]
        public async Task<IActionResult> AddOrEdit(Guid? id, GateExitCrudWithList gateExitCrudWithListModel)
        {
            var model = gateExitCrudWithListModel.GateExit;
            if (id == null)
            {
                var dateTime = new DateTime(model.Date.Value.Year,
                    model.Date.Value.Month,
                    model.Date.Value.Day,
                    model.Hour.Value,
                    model.Minute.Value,
                    0);
                var postData = new CreateGateExitDto()
                {
                    GateId = model.GateId.Value,
                    NumberOfPeople = model.NumberOfPeople.Value,
                    TimeStamp = dateTime
                };
                var endpoint = ApiEndpoints.baseUrl + ApiEndpoints.gateExitCreate;
                await _httpClientService.CreateAsync(model, postData, endpoint);
            }
            else
            {
                var dateTime = new DateTime(model.Date.Value.Year,
                    model.Date.Value.Month,
                    model.Date.Value.Day,
                    model.Hour.Value,
                    model.Minute.Value,
                    0);
                var postData = new UpdateGateExitDto()
                {
                    Id = model.Id.Value,
                    NumberOfPeople = model.NumberOfPeople.Value,
                    TimeStamp = dateTime
                };
                var endpoint = ApiEndpoints.baseUrl + ApiEndpoints.gateExitEdit;
                await _httpClientService.EditAsync(model, postData, endpoint);
            }
            return RedirectToAction("GetAll");
        }

        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id != null)
            {
                var endpoint = ApiEndpoints.baseUrl + ApiEndpoints.gateExitDelete.Replace("{id}", "") + id;
                await _httpClientService.DeleteAsync(endpoint);
            }
            return RedirectToAction("GetAll");
        }
    }
}

Controllers/GateModalController.cs
using GateEntryExit_MVC.Services.Gate;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace GateEntryExit_MVC.Controllers
{
    public class GateModalController : Controller
    { 
        private readonly IGateService _gateService;

        public GateModalController(IGateService gateService)
        {
            _gateService = gateService;
        }

        [HttpPost]
        public async Task<IActionResult> FetchGates(int pageNumber = 1,
            bool isSingleSelection = true,  
            Guid? selectedGateValue = null,
            [FromBody] Guid[] selectedGateValues = null)
        {
            var allGates = await _gateService.GetAllAsync(pageNumber);
            Guid[] gateIds = new Guid[0];

            if (selectedGateValues != null)
            {
                gateIds = selectedGateValues;
            }

            return View(new { 
                gates = allGates, 
                selectedGate = selectedGateValue,
                selectedGates = gateIds,
                isSingleSelect = isSingleSelection 
            });
        }
    }
}

ViewComponents/PaginationViewComponent.cs
using GateEntryExit_MVC.Models.Shared;
using Microsoft.AspNetCore.Mvc;

namespace GateEntryExit_MVC.ViewComponents
{
    public class PaginationViewComponent : ViewComponent
    {
        public PaginationViewComponent()
        {
            
        }

        public async Task<IViewComponentResult> InvokeAsync(PaginationModel model)
        {
            return View("~/ViewComponents/PaginationView.cshtml", model);
        }
    }
}

Views/GateExit/GetAll.cshtml
@using GateEntryExit_MVC.Models.GateExit
@using GateEntryExit_MVC.Models.Shared

@model GateExitCrudWithList

@{
    var totalItems = Model.GateExits.TotalCount;
    var items = Model.GateExits.Items;
}


<div class="container">
    <div class="row">
        <div class="col-6">
           
            <h3>Gate exit</h3>

            <div class="row">
                <div class="col-md-12">
                    <form asp-controller="GateExit" asp-action="AddOrEdit" method="post" asp-route-id="@Model.GateExit.Id">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <input type="hidden" asp-for="GateExit.Id" />

                        <div class="form-group">
                            <label>Number of people</label>
                            <input type="number" asp-for="GateExit.NumberOfPeople" placeholder="Number of people" class="form-control" />
                            <span asp-validation-for="GateExit.NumberOfPeople" class="text-danger"></span>
                        </div>

                        <div class="form-group">
                            <div>
                                <label>Time stamp</label>
                            </div>
                            <div>
                                <input type="date" asp-for="GateExit.Date" placeholder="Date" />
                                <input type="number" asp-for="GateExit.Hour" min="00" max="24" placeholder="Hour" />
                                <input type="number" asp-for="GateExit.Minute" min="00" max="59" placeholder="Minute" />
                            </div>
                        </div>

                        <input type="hidden" asp-for="GateExit.GateId" id="selectedGateValue" />
                        <div class="form-group">
                            <div class="input-group mb-3">
                                <input disabled asp-for="GateExit.GateName" class="form-control" id="selectedGateName" placeholder="Select a gate" />
                                <div class="input-group-append">
                                    <button class="btn btn-primary" onclick="showGateModal(event, '@Url.Action("FetchGates", "GateModal", new { pageNumber = 1 }, Context.Request.Scheme)','All gates', true, false)">Gates</button>
                                </div>
                            </div>
                            <span asp-validation-for="GateExit.GateName" class="text-danger"></span>
                        </div>

                        @await Html.PartialAsync("~/Views/Shared/PartialViews/GateModalPartialView.cshtml")

                        <div class="form-group mt-3">
                            <input type="submit" value="Save" class="btn btn-primary" />
                        </div>
                    </form>
                </div>
            </div>

            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Actions</th>
                        <th>
                            Name
                        </th>
                        <th>
                            NumberOfPeople
                        </th>
                        <th>
                            TimeStamp
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var gateExit in items)
                    {
                        <tr>
                            <td>
                                <button class="btn btn-primary" onclick="location.href='@Url.Action("Edit", "GateExit", new { id = gateExit.Id, pageNumber = Model.PageNumber }, Context.Request.Scheme)'">Edit</button>
                                <button class="btn btn-danger" onclick="location.href='@Url.Action("Delete", "GateExit", new { id = gateExit.Id }, Context.Request.Scheme)' ">Delete</button>
                            </td>
                            <td>@gateExit.GateName</td>
                            <td>@gateExit.NumberOfPeople</td>
                            <td>@gateExit.TimeStamp</td>
                        </tr>
                    }
                </tbody>
            </table>
            @await Component.InvokeAsync("Pagination", new PaginationModel(){
                   Controller = "GateExit",
                   Action = "GetAll",
                   TotalItems = totalItems
            })
        </div>
    </div>
</div>
   